name = Wallmapu Articulos
description = Un layout para usar en la vista de articulos y contenidos en sitio Mapuexpress.org
preview = preview.png
template = wallmapu-articulos-layout

regions[branding]       = Marca
regions[principal]	= Barra de Usuario
regions[banner]		= Banner
regions[navigation]     = Barra de Navegación
regions[highlighted]    = Destacados
regions[help]           = Ayuda
regions[content]        = Contenido
regions[sidebar_right] = Lateral Derecha
regions[pre_footer_1]   = Pre Footer-1
regions[pre_footer_2]   = Pre Footer-2
regions[pre_footer_3]   = Pre Footer-3
regions[footer]         = Footer


; Stylesheets
stylesheets[all][] = css/layouts/wallmapu-articulos/wallmapu-articulos.layout.css
stylesheets[all][] = css/layouts/wallmapu-articulos/wallmapu-articulos.layout.no-query.css
stylesheets[all][] = css/layouts/wallmapu-articulos/tekulwun-wallmapu-articulos.layout.css
